name: Deploy To Cloudflare Pages

# on:
#   schedule:
#     - cron: "0 5 * * *" # 毎日5時に実行
#   push:
#     branches:
#       - 'main'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    name: Deploy To Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
      - name: tetst
        run:  echo ${{ github.workspace }}/dist
      - nae: ss
        run: echo ${{ github.workspace }}
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ github.workspace }}/dist --project-name=tech-herb
