name: Deploy To Cloudflare Pages

# on: [push]
#   # schedule:
#   #   - cron: "0 5 * * *" # 毎朝5時に更新

on:
  schedule:
    - cron: "0 5 * * *" # 毎朝5時に更新
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-24.04
    name: Deploy To Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ github.workspace }} --project-name=tech-herb
